Clean up

diff --git a/aports/main/postmarketos-android-recovery-installer/pmos_chroot b/aports/main/postmarketos-android-recovery-installer/pmos_chroot
--- a/aports/main/postmarketos-android-recovery-installer/pmos_chroot
+++ b/aports/main/postmarketos-android-recovery-installer/pmos_chroot
@@ -1,14 +1,41 @@
 #!/sbin/sh
-set -e
+exec > /tmp/postmarketos/pmos_chroot.log 2>&1
+set -ex
+
 export CHROOT="/tmp/postmarketos/chroot"
-unzip "$ZIP" chroot/* -d "/tmp/postmarketos"
+
+# Extract chroot
+unzip "$ZIP" chroot/* -d /tmp/postmarketos
+
+# shellcheck source=/dev/null
+. "$CHROOT"/install_options
+if [ "$FDE" = 'true' ]
+then
+	# Install password setting script
+	{
+		echo '#!/sbin/sh'
+		echo "chroot $CHROOT /bin/pmos_setpw"
+	} > /sbin/pmos_setpw
+	chmod 755 /sbin/pmos_setpw
+fi
+
+# Mount pmos.zip and recovery.fstab, so we can access them inside the chroot
 touch "$CHROOT"/pmos.zip
 mount --bind "$ZIP" "$CHROOT"/pmos.zip
+mount --bind /etc/recovery.fstab "$CHROOT"/recovery.fstab || \
+	[ "$?" = '255' ] && echo 'recovery.fstab not found, continuing...' || return "$?"
+
+# Mount necessary filesystems for the chroot
 for mountpoint in "/dev" "/proc" "/sys"
 do
 	mkdir -p "$CHROOT""$mountpoint"
 	mount --bind "$mountpoint" "$CHROOT""$mountpoint"
 done
+
+# Set permissions and start the installation script
 chmod 755 "$CHROOT"/bin/*
-chmod 755 "$CHROOT"/lib/*
-chroot "$CHROOT" /bin/pmos_install
+chroot "$CHROOT" /bin/pmos_install || {
+	echo 'Installation script failed.'
+	echo 'Check /tmp/postmarketos/chroot/pmos.log for more information.'
+	return 1
+}
